-- This migration was generated before member auth base tables existed in
-- replay order. It caused production deploys to fail by referencing
-- auth_accounts/auth_tokens before 20260329110000_add_member_identity_auth.
--
-- Keep this migration as a no-op to preserve history and ordering; the real
-- auth/external-auth schema is applied in:
--   20260329110000_add_member_identity_auth
--   20260329113000_rebased_external_auth_and_auth_events
